services:
  bot:
    build: .
    container_name: anon-questions-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - bot_database:/data 
      - ./data:/data # Persist SQLite database
      - ./logs:/logs # Persist logs

    mem_limit: 128m
    cpus: 0.3
    mem_reservation: 32m

volumes:
  bot_database:

networks:
  bot-network:
    driver: bridge
