# environment.yml

# Name of the conda environment
name: anon-questions-bot

# Channels to search for packages. conda-forge is preferred for many community packages.
channels:
  - conda-forge
  - defaults

# List of dependencies
dependencies:
  # Specify the Python version for consistency
  - python=3.10

  # Database drivers and ORM
  - sqlalchemy=2.0.25 # Corresponds to sqlalchemy[asyncio]
  - asyncpg=0.29.0
  
  # Environment variables
  - python-dotenv=1.0.0

  # Development and testing dependencies
  - pytest=7.4.3
  - pytest-asyncio=0.21.1

  # We need pip for packages not available on conda channels
  - pip
  
  # Packages to be installed with pip
  - pip:
    - aiogram==3.4.1 # aiogram is best installed via pip to get the latest versions
  - pip:
    - sentry-sdk=2.29.1  